{% set name = "pymodbus" %}
{% set version = "3.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymodbus-{{ version }}.tar.gz
  sha256: 82787121e293f31095c0e9721b3e561a01807a6ac20abcbfb187ce70d24fb40c

build:
  number: 0
  noarch: python
  entry_points:
    - pymodbus.console=pymodbus.repl.client.main:main
    - pymodbus.server=pymodbus.repl.server.main:app
    - pymodbus.simulator=pymodbus.server.simulator.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - aiohttp >=3.8.3
    - typer >=0.7.0
    - prompt_toolkit >=3.0.36
    - pygments >=2.14.0
    - pyserial >=3.5

test:
  imports:
    - pymodbus
    - pymodbus.client
  requires:
    - pip
  commands:
    - pymodbus.console --help
    - pymodbus.server --help
    - pymodbus.simulator --help

about:
  home: https://github.com/riptideio/pymodbus/
  summary: A fully featured modbus protocol stack in python
  doc_url: https://pymodbus.readthedocs.io
  dev_url: https://github.com/riptideio/pymodbus
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - saibhargav1508
    - beenje
