{% set name = "pymodbus" %}
{% set version = "2.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymodbus-{{ version }}.tar.gz
  sha256: 24ff600245b7cc9f4e299d7099eda5f35d000707bec3429f7bd6690637c22cd5

build:
  number: 0
  noarch: python
  entry_points:
    - pymodbus.console=pymodbus.repl.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - pyserial >=3.4
    - python
    - six >=1.11.0
    - click
    - prompt_toolkit

test:
  imports:
    - pymodbus
    - pymodbus.client
  requires:
    - pip
  commands:
    - pymodbus.console --help
    - pip check

about:
  home: https://github.com/riptideio/pymodbus/
  summary: A fully featured modbus protocol stack in python
  doc_url: https://pythonhosted.org/pymodbus/
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - saibhargav1508
