{% set name = "pymodbus" %}
{% set version = "3.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymodbus-{{ version }}.tar.gz
  sha256: bda3af882b1a3e877747d7bf48d394df27895dc1493ccb9e7a147b31cca63d32

build:
  number: 0
  noarch: python
  entry_points:
    - pymodbus.console=pymodbus.repl.client.main:main
    - pymodbus.server=pymodbus.repl.server.main:app
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - aiohttp >=3.8.1
    - typer >=0.6.1
    - prompt_toolkit >=3.0.8
    - pyserial >=3.5
    - pyserial-asyncio >=0.6

test:
  imports:
    - pymodbus
    - pymodbus.client
  requires:
    - pip
  commands:
    - pymodbus.console --help
    - pymodbus.server --help
    - pip check

about:
  home: https://github.com/riptideio/pymodbus/
  summary: A fully featured modbus protocol stack in python
  doc_url: https://pymodbus.readthedocs.io
  dev_url: https://github.com/riptideio/pymodbus
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - saibhargav1508
    - beenje
