{% set name = "pymodbus" %}
{% set version = "3.8.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pymodbus-{{ version }}.tar.gz
  sha256: aa00306844c2bb962c0f583f60510be9923ce20df8debb1a4565a0a48ee00f6e

build:
  number: 0
  noarch: python
  entry_points:
    - pymodbus.simulator=pymodbus.server.simulator.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - aiohttp >=3.8.6
    - pyserial >=3.5

test:
  imports:
    - pymodbus
    - pymodbus.client
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pymodbus.simulator --help

about:
  home: https://github.com/pymodbus-dev/pymodbus
  summary: A fully featured modbus protocol stack in python
  doc_url: https://pymodbus.readthedocs.io
  dev_url: https://github.com/pymodbus-dev/pymodbus
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - saibhargav1508
    - beenje
