{% set name = "pymodbus" %}
{% set version = "3.6.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymodbus-{{ version }}.tar.gz
  sha256: f4223b72c20cd00a2cf25f6ddb31ecb2c0587309111a55283b2f4a1ac115e4cc

build:
  number: 0
  noarch: python
  entry_points:
    - pymodbus.simulator=pymodbus.server.simulator.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - python >=3.9
    - aiohttp >=3.8.6
    - pyserial >=3.5

test:
  imports:
    - pymodbus
    - pymodbus.client
  requires:
    - pip
  commands:
    - pymodbus.simulator --help

about:
  home: https://github.com/pymodbus-dev/pymodbus
  summary: A fully featured modbus protocol stack in python
  doc_url: https://pymodbus.readthedocs.io
  dev_url: https://github.com/pymodbus-dev/pymodbus
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - saibhargav1508
    - beenje
