{% set name = "pymodbus" %}
{% set version = "3.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymodbus-{{ version }}.tar.gz
  sha256: 714e5d6b7e28c4016a94346e73033aff276b6ce8bd22e470ba4fd8b982e08a98
  patches:
    - 0001-main-should-be-sync-1339.patch

build:
  number: 0
  noarch: python
  entry_points:
    - pymodbus.console=pymodbus.repl.client.main:main
    - pymodbus.server=pymodbus.repl.server.main:app
    - pymodbus.simulator=pymodbus.server.simulator.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - aiohttp >=3.8.1
    - typer >=0.6.1
    - prompt_toolkit >=3.0.8
    - pygments >=2.12.0
    - pyserial >=3.5
    - pyserial-asyncio >=0.6

test:
  imports:
    - pymodbus
    - pymodbus.client
  requires:
    - pip
  commands:
    - pymodbus.console --help
    - pymodbus.server --help
    - pymodbus.simulator --help
    - pip check

about:
  home: https://github.com/riptideio/pymodbus/
  summary: A fully featured modbus protocol stack in python
  doc_url: https://pymodbus.readthedocs.io
  dev_url: https://github.com/riptideio/pymodbus
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - saibhargav1508
    - beenje
