{% set name = "pymodbus" %}
{% set version = "3.6.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pymodbus-{{ version }}.tar.gz
  sha256: df51ddd790101640418ee740665c611a07bb11eca61610f2aa398db39426dc16

build:
  number: 0
  noarch: python
  entry_points:
    - pymodbus.simulator=pymodbus.server.simulator.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - aiohttp >=3.8.6
    - pyserial >=3.5

test:
  imports:
    - pymodbus
    - pymodbus.client
  requires:
    - pip
  commands:
    - pymodbus.simulator --help

about:
  home: https://github.com/pymodbus-dev/pymodbus
  summary: A fully featured modbus protocol stack in python
  doc_url: https://pymodbus.readthedocs.io
  dev_url: https://github.com/pymodbus-dev/pymodbus
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - saibhargav1508
    - beenje
